CREATE DATABASE PIZZA_DB;
USE PIZZA_DB;

CREATE OR REPLACE TABLE PIZZA_SALES;
(PIZZA_ID INT,
ORDER_ID INT,
PIZZA_NAME_ID VARCHAR(50),
QUANTITY INT,
ORDER_DATE VARCHAR(20),
ORDER_TIME TIME,
UNIT_PRICE NUMBER(5,2),
TOTAL_PRICE NUMBER(5,2),
PIZZA_SIZE VARCHAR(5),
PIZZA_CATEGORY VARCHAR(50),
PIZZA_INGREDIENTS VARCHAR(100),
PIZZA_NAME VARCHAR(100));

SELECT * FROM PIZZA_SALES;

UPDATE PIZZA_SALES SET ORDER_DATE = TO_DATE(ORDER_DATE, 'DD-MM-YYYY');


--KPIS

--TOTAL REVENUE

SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE 
FROM PIZZA_SALES;

--AVERAGE_ORDER_VALUE

SELECT ROUND(SUM(TOTAL_PRICE)/COUNT(DISTINCT ORDER_ID),2) AS AVG_ORDER_VALUE 
FROM PIZZA_SALES;

--TOTAL_PIZZAS_SOLD

SELECT SUM(QUANTITY) AS TOTAL_PIZZA FROM PIZZA_SALES;

--TOTAL_ORDERS

SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS 
FROM PIZZA_SALES;

--AVG_PIZZA_PER_ORDER

SELECT ROUND(SUM(QUANTITY)/COUNT(DISTINCT ORDER_ID),2) AS AVG_PIZZA_PER_ORDER
FROM PIZZA_SALES;

--DAILY TREND OF ORDERS

SELECT DAYNAME(ORDER_DATE), COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY 1
ORDER BY 2 DESC;

--MONTHLY TREND OF ORDERS

SELECT DISTINCT TO_CHAR(TO_DATE(ORDER_DATE), 'MON'), COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY 1
ORDER BY 2 DESC;

--%age OF SALES BY PIZZA CATEGORY

SELECT * FROM PIZZA_SALES;

SELECT PIZZA_CATEGORY, ROUND((SUM(TOTAL_PRICE)/(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES))*100,2) AS PERCENTAGE_SALES
FROM PIZZA_SALES
GROUP BY 1; 

----%age OF SALES BY PIZZA SIZE

SELECT PIZZA_SIZE, ROUND((SUM(TOTAL_PRICE)/(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES))*100,2) AS PERCENTAGE_SALES
FROM PIZZA_SALES
GROUP BY 1;

--TOTAL PIZZA SOLD BY PIZZA CATEGORY

SELECT PIZZA_CATEGORY, SUM(QUANTITY) AS TOTAL_PIZZA_SOLD
FROM PIZZA_SALES
GROUP BY 1;

--TOP 5 PIZZA BY REVENUE

SELECT PIZZA_NAME, SUM(TOTAL_PRICE)
FROM PIZZA_SALES
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

--BOTTOM 5 PIZZAS BY REVENUE

SELECT PIZZA_NAME, SUM(TOTAL_PRICE)
FROM PIZZA_SALES
GROUP BY 1
ORDER BY 2
LIMIT 5;

--BOTTOM 5 PIZZA BY QUANTITY

SELECT PIZZA_NAME, SUM(QUANTITY)
FROM PIZZA_SALES
GROUP BY 1
ORDER BY 2
LIMIT 5;

--TOP 5 PIZZA BY TOTAL ORDERS

SELECT PIZZA_NAME, COUNT(DISTINCT ORDER_ID)
FROM PIZZA_SALES
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

--BOTTOM 5 PIZZA BY TOTAL ORDERS

SELECT PIZZA_NAME, COUNT(DISTINCT ORDER_ID)
FROM PIZZA_SALES
GROUP BY 1
ORDER BY 2
LIMIT 5;

