
-----------------------STORAGE INTEGRATION------------------------
CREATE OR REPLACE STORAGE INTEGRATION czechbank_integration
TYPE = external_stage
STORAGE_PROVIDER = S3
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::659047041382:role/czechbankdatarole'
ENABLED = true
Storage_ALLOWED_LOCATIONS = ('*');

DESCRIBE integration czechbank_integration;

-----------------------------CREATE STAGE---------------------
CREATE OR REPLACE STAGE BANK
URL ='s3://czechbankdata21/'
file_format = CSV_FILE
storage_integration = czechbank_integration;

SHOW STAGES;
LIST @BANK;

-----------------------CREATE PIPE---------------------------
CREATE OR REPLACE PIPE  BANK_SNOWPIPE_ACCOUNT AUTO_INGEST = TRUE AS
COPY INTO BANK.PUBLIC.ACCOUNT
FROM '@BANK/account/'
FILE_FORMAT = CSV_FILE;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_CARD AUTO_INGEST = TRUE AS
COPY INTO BANK.PUBLIC.CARD
FROM '@BANK/card/'
FILE_FORMAT = CSV_FILE;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_CLIENT AUTO_INGEST = TRUE AS
COPY INTO BANK.PUBLIC.CLIENT
FROM '@BANK/client/'
FILE_FORMAT = CSV_FILE;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_DISPOSITION AUTO_INGEST = TRUE AS
COPY INTO BANK.PUBLIC.DISPOSITION
FROM '@BANK/disposition/'
FILE_FORMAT = CSV_FILE;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_DISTRICT AUTO_INGEST = TRUE AS
COPY INTO BANK.PUBLIC.DISTRICT
FROM '@BANK/district/'
FILE_FORMAT = CSV_FILE;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_LOAN AUTO_INGEST = TRUE AS
COPY INTO BANK.PUBLIC.LOAN
FROM '@BANK/loan/'
FILE_FORMAT = CSV_FILE;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_ORDERS AUTO_INGEST = TRUE AS
COPY INTO BANK.PUBLIC.ORDERS
FROM '@BANK/order/'
FILE_FORMAT = CSV_FILE;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_TRANSACTIONS AUTO_INGEST = TRUE AS
COPY INTO BANK.PUBLIC.TRANSACTIONS
FROM '@BANK/transaction/'
FILE_FORMAT = CSV_FILE;

SHOW PIPES;

SELECT count(*) FROM DISTRICT;
SELECT count(*) FROM ACCOUNT;
SELECT count(*) FROM TRANSACTIONS;
SELECT count(*) FROM DISPOSITION;
SELECT count(*) FROM CARD;
SELECT count(*) FROM ORDERS;
SELECT count(*) FROM LOAN;
SELECT count(*) FROM CLIENT;

ALTER PIPE BANK_SNOWPIPE_DISTRICT refresh;

ALTER PIPE BANK_SNOWPIPE_ACCOUNT refresh;

ALTER PIPE BANK_SNOWPIPE_TRANSACTIONS refresh;

ALTER PIPE BANK_SNOWPIPE_DISPOSITION refresh;

ALTER PIPE BANK_SNOWPIPE_CARD refresh;

ALTER PIPE BANK_SNOWPIPE_ORDERS refresh;

ALTER PIPE BANK_SNOWPIPE_LOAN refresh;

ALTER PIPE BANK_SNOWPIPE_CLIENT refresh;