CREATE OR REPLACE TASK BANKING_KPI
WAREHOUSE = COMPUTE_WH
SCHEDULE = '2 MINUTE'
AS CALL BANKING_KPI_PROC();

CREATE OR REPLACE TASK ACC_LATEST_TXNS
WAREHOUSE = COMPUTE_WH
SCHEDULE = '5 MINUTE'
AS CALL ACCOUNT_LASTEST_TXN();

SHOW TASKS;

ALTER TASK ACC_LATEST_TXNS RESUME;
ALTER TASK ACC_LATEST_TXNS SUSPEND;
ALTER TASK BANKING_KPI RESUME;
ALTER TASK BANKING_KPI SUSPEND;