--------------------------ANALYSIS----------------------------------

--WHICH COUNTRY HAS THE HIGHEST NUMBER OF COVID CASES

SELECT COUNTRY, SUM(TOTAL_CASES) AS TOTAL_CASES
FROM COVID_DATA
GROUP BY 1
HAVING SUM(TOTAL_CASES) IS NOT NULL
ORDER BY 2 DESC;

--COUNTRY WITH NO COVID CASES

SELECT COUNTRY FROM
(SELECT COUNTRY, SUM(TOTAL_CASES) AS TOTAL_CASES
FROM COVID_DATA
GROUP BY 1
HAVING SUM(TOTAL_CASES) IS NULL);

--COUNTRY WITH HIGHEST DEATH AND DEATH %AGE

SELECT COUNTRY, TOTAL_DEATHS, TOTAL_DEATHS/TOTAL_CASES*100 AS DEATH_PERECENT FROM
(SELECT COUNTRY, SUM(TOTAL_DEATHS) AS TOTAL_DEATHS, SUM(TOTAL_CASES) AS TOTAL_CASES
FROM COVID_DATA
GROUP BY 1
HAVING SUM(TOTAL_DEATHS) IS NOT NULL)
ORDER BY 2 DESC, 3 DESC; 

--YEAR AND MONTH WITH HIGHEST NUMBER OF CASES

SELECT YEAR, MONTH FROM
(SELECT YEAR(DATE) AS YEAR, MONTH(DATE) AS MONTH, DENSE_RANK() OVER(PARTITION BY YEAR(DATE) ORDER BY SUM(TOTAL_CASES) DESC) AS RNK
FROM COVID_DATA
GROUP BY 1,2)
WHERE RNK = 1 ;

--YEAR AND MONTH WITH HIGHEST NUMBER OF DEATHS

SELECT YEAR, MONTH FROM
(SELECT YEAR(DATE) AS YEAR, MONTH(DATE) AS MONTH, DENSE_RANK() OVER(PARTITION BY YEAR(DATE) ORDER BY SUM(TOTAL_DEATHS) DESC) AS RNK
FROM COVID_DATA
GROUP BY 1,2)
WHERE RNK = 1 ;

--COUNTRY WITH HIGHEST RECOVERY %AGE

SELECT COUNTRY, ROUND(RECOVERY/TOTAL_CASES*100,2) AS RECOVERY_RATE FROM
(SELECT COUNTRY, SUM(TOTAL_CASES) AS TOTAL_CASES,  SUM(TOTAL_CASES) - COALESCE(SUM(TOTAL_DEATHS), 0) AS RECOVERY
FROM COVID_DATA
GROUP BY 1 
ORDER BY 2 DESC)
WHERE RECOVERY_RATE IS NOT NULL
ORDER BY RECOVERY_RATE DESC;

--COUNTRY WITH NO DEATHS

SELECT COUNTRY, SUM(TOTAL_DEATHS)
FROM COVID_DATA
GROUP BY 1
HAVING SUM(TOTAL_DEATHS) IS NULL;

--CONTINENT WITH HIGHEST CASES AND DEATHS

SELECT CONTINENT, SUM(TOTAL_CASES)AS TOTAL_CASES, SUM(TOTAL_DEATHS) AS TOTAL_DEATHS
FROM COVID_DATA
GROUP BY 1
ORDER BY 2 DESC, 3 DESC;

--COUNTRY WITH HIGHEST TESTS

SELECT COUNTRY, SUM(TOTAL_TESTS) AS TOTAL_TESTS
FROM COVID_DATA
GROUP BY 1
HAVING SUM(TOTAL_TESTS) IS NOT NULL
ORDER BY 2 DESC;

--YEAR WITH MAXIMUM CASES

SELECT YEAR(DATE) AS YEAR, SUM(TOTAL_CASES)AS TOTAL_CASES
FROM COVID_DATA
GROUP BY 1
ORDER BY 2 DESC;

----YEAR WITH MAXIMUM DEATHS

SELECT YEAR(DATE) AS YEAR, SUM(TOTAL_DEATHS) AS TOTAL_DEATHS
FROM COVID_DATA
GROUP BY 1
ORDER BY 2 DESC;

--TOTAL VACCINATION ADMINISTERED

SELECT SUM(TOTAL_VACCINATIONS) AS TOTAL_VACCINATIONS
FROM COVID_DATA;

--MAXIMUM NUMBER OF FULLY VACCINATED PEOPLE ARE IN WHICH COUNTRY

SELECT COUNTRY, SUM(PEOPLE_FULLY_VACCINATED) AS FULLY_VACCINATED
FROM COVID_DATA
GROUP BY 1
HAVING SUM(PEOPLE_FULLY_VACCINATED) IS NOT NULL
ORDER BY 2 DESC;

----MAXIMUM NUMBER OF PARTIALLY VACCINATED PEOPLE ARE IN WHICH COUNTRY

SELECT COUNTRY, SUM(PEOPLE_VACCINATED) AS PARTIALLY_VACCINATED
FROM COVID_DATA
GROUP BY 1
HAVING SUM(PEOPLE_VACCINATED) IS NOT NULL
ORDER BY 2 DESC;

--MAXIMUM BOOSTER SHOTS

SELECT COUNTRY, SUM(TOTAL_BOOSTERS) AS BOOSTER_SHOTS
FROM COVID_DATA
GROUP BY 1
HAVING SUM(TOTAL_BOOSTERS) IS NOT NULL
ORDER BY 2 DESC;